parent=base
import=common/keycloak
name=Invest Lab Email Theme
description=InvestLab custom email templates theme

brandName=InvestLab
brandTagline=InvestLab – Learn, Practice, Analyze, Then Invest.
supportEmail=support@investlab.com
companyName=InvestLab Inc.
